# ##############################################################################
# The contents of this file are subject to the PyTis Public License Version    #
# 2.0 (the "License"); you may not use this file except in compliance with     #
# the License. You may obtain a copy of the License at                         #
#                                                                              #
#     http://www.PyTis.com/License/                                            #
#                                                                              #
#     Copyright (c) 2018 Josh Lee                                              #
#                                                                              #
# Software distributed under the License is distributed on an "AS IS" basis,   #
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License     #
# for the specific language governing rights and limitations under the         #
# License.                                                                     #
#                                                                              #
# @auto-generated by the PyTis Copyright Tool on 06:23 04 Apr, 2018            #
############################################################################## #
import sys

python_version = float("%s.%s"%(sys.version_info.major,sys.version_info.minor))


if python_version >= 3.0:
	from . import pytis as PyTis
else:
	import pytis as PyTis

__all__ = ['python_version', 'PyTis']

